### ISSUE TITLE
Distant object rendered incorrectly.

### ISSUE THREAD

**Issue by KokeCacao** [misode/deepslate#60]
Before Fix:
![Image](https://github.com/user-attachments/assets/28e61e99-c664-4e28-b113-942dfdaef34f)

After Fix:
![Image](https://github.com/user-attachments/assets/284f7b44-2df4-4772-a4ca-2bc51f317b94)

Why it Happens: Incorrect MipMap level blends alpha channel.

The Fix:
```
  protected createAtlasTexture(image: ImageData) {

    const texture = this.gl.createTexture()!
    this.gl.bindTexture(this.gl.TEXTURE_2D, texture)

    const ext = this.gl.getExtension('EXT_texture_filter_anisotropic')
    || this.gl.getExtension('MOZ_EXT_texture_filter_anisotropic')
    || this.gl.getExtension('WEBKIT_EXT_texture_filter_anisotropic');
    if (ext) {
      this.gl.texParameterf(
        this.gl.TEXTURE_2D,
        ext.TEXTURE_MAX_ANISOTROPY_EXT,
        4  // try 2, 4, 8, or 16 depending on performance/quality balance
      );
    }

    this.gl.texImage2D(this.gl.TEXTURE_2D, 0, this.gl.RGBA, this.gl.RGBA, this.gl.UNSIGNED_BYTE, image)

    // only sample up to mip level 4 because Minecraft block texture usually 16x16 pixels
    this.gl.texParameteri(this.gl.TEXTURE_2D, this.gl.TEXTURE_BASE_LEVEL, 0);
    this.gl.texParameteri(this.gl.TEXTURE_2D, this.gl.TEXTURE_MAX_LEVEL, 4);

    // linear blend between the two closest mipmap levels, nearest texel in each.
    this.gl.texParameteri(this.gl.TEXTURE_2D, this.gl.TEXTURE_MIN_FILTER, this.gl.NEAREST_MIPMAP_LINEAR)
    this.gl.texParameteri(this.gl.TEXTURE_2D, this.gl.TEXTURE_MAG_FILTER, this.gl.NEAREST)

    this.gl.generateMipmap(this.gl.TEXTURE_2D)

    return texture
  }
```

I can draft a PR if you wish.

**Comment by misode** [comment]
@KokeCacao Can you check whether this is also fixed by #61?

**Comment by KokeCacao** [comment]
#61 only
<img width="1920" height="320" alt="Image" src="https://github.com/user-attachments/assets/22743dda-1e3b-4abb-af51-89938739f9a5" />

This is kinda bad, although much better than the unfixed version in "Before Fix (none)" image, most of the grass region is still not fully opaque.

#60 + #61
<img width="1920" height="320" alt="Image" src="https://github.com/user-attachments/assets/5d3d63a1-fd18-4ae2-bc49-ab22a3c2e293" />

I would expect this to be better than "After Fix (#60)", but it is not. Not sure why, but it missed 9 pixels in the grass region, but otherwise it is near perfect.

Note that none of our solutions could make the top edge of the grass plane (the 4th and 6th sub-image) fully opaque. Not sure why or whether it is a bug.

(Also, there is an inconsistency of using tabs instead of spaces. Can we make a standard by having some auto formatting?)
